### ISSUE TITLE
Database Problem

### ISSUE THREAD

**Issue by codeinferno1** [Prathamesh-Patil-GitHub/mothers-dish#1]
You should provide a database template

**Comment by Prathamesh-Patil-GitHub** [comment]
Hey mate, What do you mean by a database template?

**Comment by codeinferno1** [comment]
I just went through your project code and found that you have used local database (MySQL database) . So I want to tell you that it would be great if you provide a template (exported .sql) file of your database structure . BTW follow me back :(

**Comment by Prathamesh-Patil-GitHub** [comment]
I've added the .sql file, I hope now the problem is solved ! 😃
